name: Deploy

on: [push]
#on:
#  push:
#    tags:
#      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: nexys-system/gh-actions-spa-test@v1.0.3
        with:
          build-command: VITE_GIT_SHA=$GITHUB_SHA VITE_VERSION=${GITHUB_REF##*/} yarn build --mode ghpages
          deploy-project-name: template-tailwind
          deploy-token: ${{ secrets.DEPLOY_TOKEN }}
      - name: add 404
        run: cp dist/index.html dist/404.html
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
